import { useRef } from "react";
import { useI18n } from "../../../i18n/I18nProvider";
import type { EnergyCapacityUnit, EnergyNormalizationBasis } from "../analysis/energyPower";
import { BasisOptions } from "./EnergySummaryInput";
import { EnergyCurveFileImport } from "./EnergyCurveFileImport";

export type EnergyCurveMode = "capacity" | "time";
export interface EnergyCurvePointDraft { readonly id: string; readonly x: number | null; readonly voltage: number | null; readonly current: number | null }
export interface EnergyCurveDraft {
  readonly id: string; readonly mode: EnergyCurveMode; readonly inputMode: "manual" | "upload"; readonly sampleName: string;
  readonly points: ReadonlyArray<Readonly<EnergyCurvePointDraft>>; readonly xUnit: EnergyCapacityUnit | "s" | "min" | "h";
  readonly currentUnit: "mA" | "A" | "mA-g-1" | "A-g-1"; readonly currentSign: "positive" | "negative";
  readonly basis: EnergyNormalizationBasis; readonly massG: number | null; readonly volumeCm3: number | null;
  readonly dischargeTimeHours: number | null;
}
export const createEnergyCurveDraft = (id = "energy-curve-1"): EnergyCurveDraft => ({
  id, mode: "capacity", inputMode: "manual", sampleName: "", points: initialPoints(id), xUnit: "mAh-g-1",
  currentUnit: "mA-g-1", currentSign: "positive", basis: "active-material", massG: null,
  volumeCm3: null, dischargeTimeHours: null,
});
function initialPoints(id: string): EnergyCurvePointDraft[] { return Array.from({ length: 5 }, (_, index) => ({ id: `${id}-point-${index + 1}`, x: null, voltage: null, current: null })); }

export function EnergyCurveInput({ values, onChange }: { values: ReadonlyArray<Readonly<EnergyCurveDraft>>; onChange: (values: EnergyCurveDraft[]) => void }) {
  const { t } = useI18n(); const sequence = useRef(values.length);
  const replace = (id: string, next: EnergyCurveDraft) => onChange(values.map((value) => value.id === id ? next : clone(value)));
  function duplicate(value: Readonly<EnergyCurveDraft>) { sequence.current += 1; const id = `energy-curve-${sequence.current}`; onChange([...values.map(clone), { ...clone(value), id, sampleName: value.sampleName ? `${value.sampleName} ${t("rate.energy.input.copySuffix")}` : "", points: value.points.map((point, index) => ({ ...point, id: `${id}-point-${index + 1}` })) }]); }
  return <section className="tool-section energy-curve-input"><h2>{t("rate.energy.curve.title")}</h2><div className="energy-summary-list">{values.map((value, index) => <article className="energy-curve-sample energy-summary-sample" key={value.id} aria-labelledby={`${value.id}-heading`}><div className="energy-sample-header"><h3 id={`${value.id}-heading`}>{value.sampleName || t("rate.energy.curve.datasetNumber", { number: index + 1 })}</h3><div><button type="button" aria-label={`${t("rate.energy.input.duplicate")} ${index + 1}`} onClick={() => duplicate(value)}>{t("rate.energy.input.duplicate")}</button><button type="button" aria-label={`${t("rate.energy.input.delete")} ${index + 1}`} disabled={values.length === 1} onClick={() => onChange(values.filter(({ id }) => id !== value.id).map(clone))}>{t("rate.energy.input.delete")}</button></div></div><EnergyCurveSampleInput value={value} onChange={(next) => replace(value.id, next)} /></article>)}</div><div className="rate-manual-toolbar"><button type="button" onClick={() => { sequence.current += 1; onChange([...values.map(clone), createEnergyCurveDraft(`energy-curve-${sequence.current}`)]); }}>{t("rate.energy.input.add")}</button></div></section>;
}

function EnergyCurveSampleInput({ value, onChange }: { value: Readonly<EnergyCurveDraft>; onChange: (value: EnergyCurveDraft) => void }) {
  const { t } = useI18n(); const number = (raw: string) => raw.trim() === "" ? null : Number(raw);
  const set = <K extends keyof EnergyCurveDraft>(key: K, next: EnergyCurveDraft[K]) => onChange({ ...clone(value), [key]: next });
  function changeMode(mode: EnergyCurveMode) { onChange({ ...createEnergyCurveDraft(value.id), sampleName: value.sampleName, basis: value.basis, massG: value.massG, volumeCm3: value.volumeCm3, mode, xUnit: mode === "capacity" ? "mAh-g-1" : "s" }); }
  const replacePoint = (id: string, key: "x" | "voltage" | "current", raw: string) => set("points", value.points.map((point) => point.id === id ? { ...point, [key]: number(raw) } : { ...point }));
  function paste(event: React.ClipboardEvent<HTMLTableElement>) { const columns = value.mode === "capacity" ? 2 : 3; const rows = event.clipboardData.getData("text").trim().split(/\r?\n/).map((line) => line.trim().split(/[\t,; ]+/).slice(0, columns)); if (!rows.length || rows.some((row) => row.length !== columns || row.some((cell) => !Number.isFinite(Number(cell))))) return; event.preventDefault(); set("points", rows.map((row, rowIndex) => ({ id: `${value.id}-paste-${rowIndex + 1}`, x: Number(row[0]), voltage: Number(row[1]), current: value.mode === "time" ? Number(row[2]) : null }))); }
  return <><div className="rate-input-mode" role="radiogroup" aria-label={t("rate.energy.curve.modeLabel")}><label><input name={`${value.id}-curve-mode`} type="radio" checked={value.mode === "capacity"} onChange={() => changeMode("capacity")} />{t("rate.energy.curve.capacityMode")}</label><label><input name={`${value.id}-curve-mode`} type="radio" checked={value.mode === "time"} onChange={() => changeMode("time")} />{t("rate.energy.curve.timeMode")}</label></div><div className="rate-input-mode" role="radiogroup" aria-label={t("rate.energy.curve.inputModeLabel")}><label><input name={`${value.id}-input-mode`} type="radio" checked={value.inputMode === "manual"} onChange={() => set("inputMode", "manual")} />{t("rate.input.manual")}</label><label><input name={`${value.id}-input-mode`} type="radio" checked={value.inputMode === "upload"} onChange={() => set("inputMode", "upload")} />{t("rate.input.upload")}</label></div><CurveSettings value={value} onChange={onChange} />{value.inputMode === "manual" ? <><div className="energy-curve-table-scroll"><table className="energy-curve-table" onPaste={paste}><thead><tr><th>{value.mode === "capacity" ? t("rate.energy.input.capacity") : t("rate.energy.curve.time")}</th><th>{t("rate.energy.curve.voltage")}</th>{value.mode === "time" ? <th>{t("rate.energy.curve.current")}</th> : null}<th>{t("rate.energy.input.action")}</th></tr></thead><tbody>{value.points.map((point, rowIndex) => <tr key={point.id}><td><input aria-label={`${value.mode === "capacity" ? t("rate.energy.input.capacity") : t("rate.energy.curve.time")} ${rowIndex + 1}`} type="number" value={point.x ?? ""} onChange={(event) => replacePoint(point.id, "x", event.target.value)} /></td><td><input aria-label={`${t("rate.energy.curve.voltage")} ${rowIndex + 1}`} type="number" value={point.voltage ?? ""} onChange={(event) => replacePoint(point.id, "voltage", event.target.value)} /></td>{value.mode === "time" ? <td><input aria-label={`${t("rate.energy.curve.current")} ${rowIndex + 1}`} type="number" value={point.current ?? ""} onChange={(event) => replacePoint(point.id, "current", event.target.value)} /></td> : null}<td><button type="button" aria-label={`${t("rate.energy.input.delete")} ${rowIndex + 1}`} onClick={() => set("points", value.points.filter(({ id }) => id !== point.id).map((item) => ({ ...item })))}>{t("rate.energy.input.delete")}</button></td></tr>)}</tbody></table></div><button type="button" onClick={() => set("points", [...value.points.map((point) => ({ ...point })), { id: `${value.id}-point-${Date.now()}`, x: null, voltage: null, current: null }])}>{t("rate.ca.input.addRow")}</button></> : <EnergyCurveFileImport key={`${value.id}-${value.mode}`} sampleId={value.id} mode={value.mode} onPoints={(points) => set("points", points)} />}</>;
}

function CurveSettings({ value, onChange }: { value: Readonly<EnergyCurveDraft>; onChange: (value: EnergyCurveDraft) => void }) {
  const { t } = useI18n(); const number = (raw: string) => raw.trim() === "" ? null : Number(raw); const set = <K extends keyof EnergyCurveDraft>(key: K, next: EnergyCurveDraft[K]) => onChange({ ...clone(value), [key]: next });
  return <><div className="energy-input-grid"><label>{t("rate.energy.input.sampleName")}<input value={value.sampleName} onChange={(event) => set("sampleName", event.target.value)} /></label><label>{t("rate.energy.curve.axisUnit")}<select value={value.xUnit} onChange={(event) => set("xUnit", event.target.value as EnergyCurveDraft["xUnit"])}>{value.mode === "capacity" ? <><option value="mAh-g-1">mAh g^-1</option><option value="Ah-kg-1">Ah kg^-1</option><option value="mAh">mAh</option></> : <><option value="s">s</option><option value="min">min</option><option value="h">h</option></>}</select></label>{value.mode === "time" ? <><label>{t("rate.energy.curve.currentUnit")}<select value={value.currentUnit} onChange={(event) => set("currentUnit", event.target.value as EnergyCurveDraft["currentUnit"])}><option value="mA">mA</option><option value="A">A</option><option value="mA-g-1">mA g^-1</option><option value="A-g-1">A g^-1</option></select></label><label>{t("rate.energy.curve.currentSign")}<select value={value.currentSign} onChange={(event) => set("currentSign", event.target.value as EnergyCurveDraft["currentSign"])}><option value="positive">{t("rate.energy.curve.signPositive")}</option><option value="negative">{t("rate.energy.curve.signNegative")}</option></select></label></> : <label>{t("rate.energy.curve.durationHours")}<input name={`${value.id}-duration`} type="number" value={value.dischargeTimeHours ?? ""} onChange={(event) => set("dischargeTimeHours", number(event.target.value))} /></label>}<label>{t("rate.energy.input.basis")}<select value={value.basis} onChange={(event) => set("basis", event.target.value as EnergyNormalizationBasis)}><BasisOptions /></select></label><label>{t("rate.energy.input.mass")}<input type="number" value={value.massG ?? ""} onChange={(event) => set("massG", number(event.target.value))} /></label><label>{t("rate.energy.input.volume")}<input type="number" value={value.volumeCm3 ?? ""} onChange={(event) => set("volumeCm3", number(event.target.value))} /></label></div><p className="energy-input-note">{t("rate.energy.input.volumeHelp")} {t("rate.energy.curve.basisConsistency")}{value.mode === "time" ? ` ${t("rate.energy.curve.currentHelp")}` : ""}</p></>;
}
function clone(value: Readonly<EnergyCurveDraft>): EnergyCurveDraft { return { ...value, points: value.points.map((point) => ({ ...point })) }; }
