import { useLayoutEffect, useRef, useState } from "react";
import { parseTabularFile, TabularParseError, type TabularCell, type TabularSheet } from "../../../lib/tabularParsing";
import { useI18n } from "../../../i18n/I18nProvider";
import type { EnergyCurveMode, EnergyCurvePointDraft } from "./EnergyCurveInput";

type HeaderMode = "auto" | "header" | "data";
interface Mapping { x: number; voltage: number; current: number }
interface Parsed { readonly fileName: string; readonly sheets: ReadonlyArray<Readonly<TabularSheet>> }

export function EnergyCurveFileImport({ sampleId, mode, onPoints, parseFile = parseTabularFile }: { sampleId: string; mode: EnergyCurveMode; onPoints: (points: EnergyCurvePointDraft[]) => void; parseFile?: (file: File) => Promise<TabularSheet[]> }) {
  const { t } = useI18n(); const [parsed, setParsed] = useState<Parsed | null>(null); const [sheetIndex, setSheetIndex] = useState(0); const [headerMode, setHeaderMode] = useState<HeaderMode>("auto"); const [mapping, setMapping] = useState<Mapping>({ x: 0, voltage: 1, current: 2 }); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const generation = useRef(0); const mounted = useRef(true); const latestOnPoints = useRef(onPoints);
  useLayoutEffect(() => { latestOnPoints.current = onPoints; }, [onPoints]);
  useLayoutEffect(() => { mounted.current = true; return () => { mounted.current = false; generation.current += 1; }; }, []);
  useLayoutEffect(() => { generation.current += 1; setBusy(false); setParsed(null); setError(""); latestOnPoints.current([]); }, [mode, sampleId]);
  const sheet = parsed?.sheets[sheetIndex]; const structure = sheet ? inspect(sheet, headerMode, (column) => t("rate.import.column", { column })) : null; const adapted = parsed && sheet && structure ? adapt(sampleId, mode, structure.dataRows, mapping) : null;
  async function select(file?: File) { if (!file) return; const token = ++generation.current; setBusy(true); setError(""); setParsed(null); latestOnPoints.current([]); try { const sheets = (await parseFile(file)).filter(({ rows }) => rows.length > 0); if (!mounted.current || token !== generation.current) return; if (!sheets.length) throw new TabularParseError("emptyFile"); const next = inspect(sheets[0], headerMode, (column) => t("rate.import.column", { column })); const nextMapping = detect(next.headers, mode); setParsed({ fileName: file.name, sheets }); setSheetIndex(0); setMapping(nextMapping); latestOnPoints.current(adapt(sampleId, mode, next.dataRows, nextMapping).points); } catch (caught) { if (!mounted.current || token !== generation.current) return; setParsed(null); latestOnPoints.current([]); setError(t(caught instanceof TabularParseError && caught.code === "resourceLimitExceeded" ? "rate.import.resourceLimit" : "rate.import.parseError")); } finally { if (mounted.current && token === generation.current) setBusy(false); } }
  function apply(nextSheet: number, nextHeader: HeaderMode, nextMapping?: Mapping) { if (!parsed) return; const selected = parsed.sheets[nextSheet]; const inspected = inspect(selected, nextHeader, (column) => t("rate.import.column", { column })); const resolved = nextMapping ?? detect(inspected.headers, mode); setSheetIndex(nextSheet); setHeaderMode(nextHeader); setMapping(resolved); latestOnPoints.current(adapt(sampleId, mode, inspected.dataRows, resolved).points); }
  const summary = adapted?.summary;
  return <section className="energy-curve-file-import"><label>{t("rate.input.file")}<input type="file" accept=".csv,.txt,.xlsx" disabled={busy} onChange={(event) => void select(event.target.files?.[0])} /></label>{busy ? <p role="status" aria-live="polite">{t("rate.import.importing")}</p> : null}{error ? <p role="alert" className="tool-validation">{error}</p> : null}{parsed && sheet && structure && summary ? <><div className="energy-import-controls">{parsed.sheets.length > 1 ? <label>{t("rate.import.sheet")}<select value={sheetIndex} onChange={(event) => apply(Number(event.target.value), headerMode)}>{parsed.sheets.map((item, index) => <option key={`${index}-${item.name}`} value={index}>{item.name}</option>)}</select></label> : null}<label>{t("rate.import.headerMode")}<select aria-label={t("rate.import.headerMode")} value={headerMode} onChange={(event) => apply(sheetIndex, event.target.value as HeaderMode)}><option value="auto">{t("rate.import.headerAuto")}</option><option value="header">{t("rate.import.headerPresent")}</option><option value="data">{t("rate.import.headerAbsent")}</option></select></label></div><fieldset className="rate-column-mapping"><legend>{t("rate.import.mapping")}</legend><MappingSelect label={t("rate.energy.curve.mappedAxis")} headers={structure.headers} value={mapping.x} onChange={(x) => apply(sheetIndex, headerMode, { ...mapping, x })} /><MappingSelect label={t("rate.energy.curve.mappedVoltage")} headers={structure.headers} value={mapping.voltage} onChange={(voltage) => apply(sheetIndex, headerMode, { ...mapping, voltage })} />{mode === "time" ? <MappingSelect label={t("rate.energy.curve.mappedCurrent")} headers={structure.headers} value={mapping.current} onChange={(current) => apply(sheetIndex, headerMode, { ...mapping, current })} /> : null}</fieldset><ImportSummary fileName={parsed.fileName} sheetName={sheet.name} headers={structure.headers} mapping={mapping} mode={mode} summary={summary} /></> : null}</section>;
}

function ImportSummary({ fileName, sheetName, headers, mapping, mode, summary }: { fileName: string; sheetName: string; headers: ReadonlyArray<string>; mapping: Mapping; mode: EnergyCurveMode; summary: ReturnType<typeof adapt>["summary"] }) { const { t } = useI18n(); return <section className="rate-import-summary" aria-live="polite"><h3>{t("rate.import.summary")}</h3><dl><Item label={t("rate.import.fileName")} value={fileName} /><Item label={t("rate.import.sheetName")} value={sheetName} /><Item label={t("rate.import.detectedColumns")} value={headers.join(", ")} /><Item label={t("rate.energy.curve.mappedAxis")} value={headers[mapping.x] ?? ""} /><Item label={t("rate.energy.curve.mappedVoltage")} value={headers[mapping.voltage] ?? ""} />{mode === "time" ? <Item label={t("rate.energy.curve.mappedCurrent")} value={headers[mapping.current] ?? ""} /> : null}<Item label={t("rate.import.rows")} value={summary.rows} /><Item label={t("rate.import.valid")} value={summary.valid} /><Item label={t("rate.energy.curve.invalidPoints")} value={summary.invalid} /><Item label={t("rate.import.missing")} value={summary.missing} /><Item label={t("rate.energy.curve.axisRange")} value={formatRange(summary.xRange)} /><Item label={t("rate.energy.curve.voltageRange")} value={formatRange(summary.voltageRange)} />{mode === "time" ? <Item label={t("rate.energy.curve.currentRange")} value={formatRange(summary.currentRange)} /> : null}</dl></section>; }
function MappingSelect({ label, headers, value, onChange }: { label: string; headers: ReadonlyArray<string>; value: number; onChange: (value: number) => void }) { return <label>{label}<select aria-label={label} value={value} onChange={(event) => onChange(Number(event.target.value))}>{headers.map((header, index) => <option key={`${index}-${header}`} value={index}>{header}</option>)}</select></label>; }
function Item({ label, value }: { label: string; value: string | number }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function inspect(sheet: Readonly<TabularSheet>, mode: HeaderMode, label: (column: number) => string) { let width = 0; for (const row of sheet.rows) width = Math.max(width, row.length); const first = sheet.rows[0] ?? []; const header = mode === "header" || (mode === "auto" && looksLikeHeader(first)); const headers = Array.from({ length: width }, (_, index) => header ? String(first[index] ?? label(index + 1)).trim() || label(index + 1) : label(index + 1)); return { headers, dataRows: header ? sheet.rows.slice(1) : sheet.rows }; }
function looksLikeHeader(row: ReadonlyArray<TabularCell>) { let numeric = 0; let recognized = 0; for (const cell of row) { if (typeof cell === "number" || (typeof cell === "string" && cell.trim() && Number.isFinite(Number(cell)))) numeric += 1; else if (typeof cell === "string" && /capacity|time|voltage|current|容量|时间|电压|电流/i.test(cell)) recognized += 1; } return numeric === 0 && recognized > 0; }
function detect(headers: ReadonlyArray<string>, mode: EnergyCurveMode): Mapping { const xPattern = mode === "capacity" ? /capacity|capacit|容量/i : /time|时间/i; const find = (pattern: RegExp, fallback: number) => { const index = headers.findIndex((header) => pattern.test(header)); return index >= 0 ? index : Math.min(fallback, Math.max(0, headers.length - 1)); }; return { x: find(xPattern, 0), voltage: find(/voltage|volt|电压/i, 1), current: find(/current|电流/i, 2) }; }
function adapt(sampleId: string, mode: EnergyCurveMode, rows: ReadonlyArray<ReadonlyArray<TabularCell>>, mapping: Mapping) { let valid = 0; let missing = 0; const xs: number[] = []; const voltages: number[] = []; const currents: number[] = []; const points = rows.map((row, index) => { const x = numeric(row[mapping.x]); const voltage = numeric(row[mapping.voltage]); const current = mode === "time" ? numeric(row[mapping.current]) : null; missing += Number(isMissing(row[mapping.x])) + Number(isMissing(row[mapping.voltage])) + (mode === "time" ? Number(isMissing(row[mapping.current])) : 0); if (Number.isFinite(x) && Number.isFinite(voltage) && (mode === "capacity" || Number.isFinite(current))) { valid += 1; xs.push(x as number); voltages.push(voltage as number); if (mode === "time") currents.push(current as number); } return { id: `${sampleId}-import-${index + 1}`, x, voltage, current }; }); return { points, summary: { rows: rows.length, valid, invalid: rows.length - valid, missing, xRange: range(xs), voltageRange: range(voltages), currentRange: range(currents) } }; }
function numeric(value: TabularCell | undefined) { if (isMissing(value)) return null; const next = typeof value === "number" ? value : Number(value); return Number.isFinite(next) ? next : Number.NaN; }
function isMissing(value: TabularCell | undefined) { return value == null || (typeof value === "string" && value.trim() === ""); }
function range(values: ReadonlyArray<number>): readonly [number, number] | null { if (!values.length) return null; let min = values[0]; let max = values[0]; for (let index = 1; index < values.length; index += 1) { min = Math.min(min, values[index]); max = Math.max(max, values[index]); } return [min, max]; }
function formatRange(value: readonly [number, number] | null) { return value ? `${value[0]}–${value[1]}` : "—"; }
